use_frameworks!

target 'LifeSpace' do
  pod 'CardinalKit', :path => '../'
  
  # CK Sample Pods
  pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :commit => 'main'
  pod 'Granola', :git => 'https://github.com/CardinalKit/Granola.git', :branch => 'main'
  
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  
  pod 'MapboxMaps', '10.1.0'

end
