name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    defaults:
      run:
        working-directory: version2/LifeSpace
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
    - name: Set Mapbox credentials
      uses: extractions/netrc@v1
      with:
        machine: api.mapbox.com
        username: mapbox
        password: ${{ secrets.MAPBOX_TOKEN }}
    - name: Install Dependencies
      run: |
        gem install cocoapods
        pod install
    - name: Build
      run: xcodebuild build -workspace LifeSpace.xcworkspace -scheme LifeSpace -destination 'platform=iOS Simulator,name=iPhone 13'